package com.gdmap.dao;

import com.gdmap.model.User;
import com.gdmap.model.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_gd.t_user
     *
     * @mbggenerated Sat Sep 08 13:40:00 CST 2018
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_gd.t_user
     *
     * @mbggenerated Sat Sep 08 13:40:00 CST 2018
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_gd.t_user
     *
     * @mbggenerated Sat Sep 08 13:40:00 CST 2018
     */
    @Insert({
        "insert into s_gd.t_user (name, tel, ",
        "created_at, updated_at, ",
        "deleted_at, note)",
        "values (#{name,jdbcType=VARCHAR}, #{tel,jdbcType=VARCHAR}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{updatedAt,jdbcType=TIMESTAMP}, ",
        "#{deletedAt,jdbcType=TIMESTAMP}, #{note,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_gd.t_user
     *
     * @mbggenerated Sat Sep 08 13:40:00 CST 2018
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_gd.t_user
     *
     * @mbggenerated Sat Sep 08 13:40:00 CST 2018
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_gd.t_user
     *
     * @mbggenerated Sat Sep 08 13:40:00 CST 2018
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_gd.t_user
     *
     * @mbggenerated Sat Sep 08 13:40:00 CST 2018
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);
}