package com.gdmap.model;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_gd.t_user.id
     *
     * @mbggenerated Sat Sep 08 13:40:00 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_gd.t_user.name
     *
     * @mbggenerated Sat Sep 08 13:40:00 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_gd.t_user.tel
     *
     * @mbggenerated Sat Sep 08 13:40:00 CST 2018
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_gd.t_user.created_at
     *
     * @mbggenerated Sat Sep 08 13:40:00 CST 2018
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_gd.t_user.updated_at
     *
     * @mbggenerated Sat Sep 08 13:40:00 CST 2018
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_gd.t_user.deleted_at
     *
     * @mbggenerated Sat Sep 08 13:40:00 CST 2018
     */
    private Date deletedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_gd.t_user.note
     *
     * @mbggenerated Sat Sep 08 13:40:00 CST 2018
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_gd.t_user.id
     *
     * @return the value of s_gd.t_user.id
     *
     * @mbggenerated Sat Sep 08 13:40:00 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_gd.t_user.id
     *
     * @param id the value for s_gd.t_user.id
     *
     * @mbggenerated Sat Sep 08 13:40:00 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_gd.t_user.name
     *
     * @return the value of s_gd.t_user.name
     *
     * @mbggenerated Sat Sep 08 13:40:00 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_gd.t_user.name
     *
     * @param name the value for s_gd.t_user.name
     *
     * @mbggenerated Sat Sep 08 13:40:00 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_gd.t_user.tel
     *
     * @return the value of s_gd.t_user.tel
     *
     * @mbggenerated Sat Sep 08 13:40:00 CST 2018
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_gd.t_user.tel
     *
     * @param tel the value for s_gd.t_user.tel
     *
     * @mbggenerated Sat Sep 08 13:40:00 CST 2018
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_gd.t_user.created_at
     *
     * @return the value of s_gd.t_user.created_at
     *
     * @mbggenerated Sat Sep 08 13:40:00 CST 2018
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_gd.t_user.created_at
     *
     * @param createdAt the value for s_gd.t_user.created_at
     *
     * @mbggenerated Sat Sep 08 13:40:00 CST 2018
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_gd.t_user.updated_at
     *
     * @return the value of s_gd.t_user.updated_at
     *
     * @mbggenerated Sat Sep 08 13:40:00 CST 2018
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_gd.t_user.updated_at
     *
     * @param updatedAt the value for s_gd.t_user.updated_at
     *
     * @mbggenerated Sat Sep 08 13:40:00 CST 2018
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_gd.t_user.deleted_at
     *
     * @return the value of s_gd.t_user.deleted_at
     *
     * @mbggenerated Sat Sep 08 13:40:00 CST 2018
     */
    public Date getDeletedAt() {
        return deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_gd.t_user.deleted_at
     *
     * @param deletedAt the value for s_gd.t_user.deleted_at
     *
     * @mbggenerated Sat Sep 08 13:40:00 CST 2018
     */
    public void setDeletedAt(Date deletedAt) {
        this.deletedAt = deletedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_gd.t_user.note
     *
     * @return the value of s_gd.t_user.note
     *
     * @mbggenerated Sat Sep 08 13:40:00 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_gd.t_user.note
     *
     * @param note the value for s_gd.t_user.note
     *
     * @mbggenerated Sat Sep 08 13:40:00 CST 2018
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_gd.t_user
     *
     * @mbggenerated Sat Sep 08 13:40:00 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", tel=").append(tel);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", updatedAt=").append(updatedAt);
        sb.append(", deletedAt=").append(deletedAt);
        sb.append(", note=").append(note);
        sb.append("]");
        return sb.toString();
    }
}